### ISSUE TITLE
Getting timeouts when connecting to ES server

### ISSUE THREAD

**Issue by agstephens** [cedadev/ceda-di#27]
On badc@ingest1 I am seeing occasional timeouts when indexing. They look like:

Process Process-5504:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/ingest_software/packages/ceda-di/python/src/ceda_di/extract.py", line 160, in process_file
    self.index_properties(filename, hand)
  File "/usr/local/ingest_software/packages/ceda-di/python/src/ceda_di/extract.py", line 173, in index_properties
    id=props.properties["_id"])
  File "/usr/local/ingest_software/venv_fbs/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/ingest_software/venv_fbs/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 261, in index
    _make_path(index, doc_type, id), params=params, body=body)
  File "/usr/local/ingest_software/venv_fbs/lib/python2.7/site-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/ingest_software/venv_fbs/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 86, in perform_request
    raise ConnectionTimeout('TIMEOUT', str(e), e)
ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='jasmin-es1.ceda.ac.uk', port=9200): Read timed out. (read timeout=10))

**Comment by agstephens** [comment]
This was resolved by using only a single processor in the ES config file.
